FROM python:3.10-slim

WORKDIR /api

COPY ./api /api

# Copy requirements file and install dependencies
COPY requirements.txt /api

RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "-A", "orders", "worker", "--loglevel=info" "-c" "10"]
